# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_is_gov'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30, verbose_name='书名')),
                ('author', models.CharField(max_length=25, verbose_name='作者')),
                ('publisher', models.CharField(max_length=35, verbose_name='出版社')),
            ],
            options={
                'verbose_name_plural': '实验室拥有书籍',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20, verbose_name='研究方向')),
            ],
            options={
                'verbose_name_plural': '各实验室主攻方向',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30, verbose_name='荣誉名字')),
                ('get_time', models.DateField(verbose_name='获得时间')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Direction')),
                ('owers', models.ManyToManyField(to='user.UserProfile')),
            ],
            options={
                'verbose_name_plural': '实验室荣誉获得',
            },
        ),
        migrations.CreateModel(
            name='LabDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='该团体很懒，暂时没有介绍呢~~', max_length=3000, verbose_name='团体描述')),
            ],
            options={
                'verbose_name_plural': '实验室详情',
            },
        ),
        migrations.CreateModel(
            name='MajorTag',
            fields=[
                ('tag_name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='主攻内容标签')),
            ],
            options={
                'verbose_name_plural': '主攻内容标签(公用)',
            },
        ),
        migrations.RemoveField(
            model_name='labgroup',
            name='admin_tor',
        ),
        migrations.RemoveField(
            model_name='labgroup',
            name='desc',
        ),
        migrations.AddField(
            model_name='labgroup',
            name='admin_tors',
            field=models.ManyToManyField(related_name='admins', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='labgroup',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labgroup',
            name='member_num',
            field=models.IntegerField(default=0, verbose_name='成员数目'),
        ),
        migrations.AddField(
            model_name='labgroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='labdetail',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.LabGroup'),
        ),
        migrations.AddField(
            model_name='direction',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.LabDetail'),
        ),
        migrations.AddField(
            model_name='direction',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='direction',
            name='major_tags',
            field=models.ManyToManyField(to='group.MajorTag'),
        ),
        migrations.AddField(
            model_name='book',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.LabDetail'),
        ),
    ]
