# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20191012_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='honor',
            name='lab',
            field=models.ForeignKey(default=23333, on_delete=django.db.models.deletion.CASCADE, to='group.LabDetail'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='direction',
            field=models.ForeignKey(default='对应方向已不在', on_delete=django.db.models.deletion.SET_DEFAULT, to='group.Direction'),
        ),
    ]
