# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200520_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=10)),
                ('lab_name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=1000)),
                ('member_num', models.IntegerField()),
                ('members', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
