# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200520_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '主题的标签',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='题目')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('tags', models.ManyToManyField(to='forum.Tag')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '论坛主题',
            },
        ),
    ]
