# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='题目')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '论坛主题',
            },
        ),
    ]
