# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_is_gov'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('content', models.CharField(max_length=250, verbose_name='评论内容')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name_plural': '对于主题的评论',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '主题的标签',
            },
        ),
        migrations.AddField(
            model_name='title',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='title',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='title',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='title',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Title'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag'),
        ),
    ]
