# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191012_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(null=True, to='forum.Tag'),
        ),
    ]
