# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191012_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag'),
        ),
    ]
