# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_gov',
            field=models.NullBooleanField(verbose_name='用户身份'),
        ),
    ]
