# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Lab'),
        ),
    ]
