# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-23 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='mod_date',
        ),
    ]
